### ISSUE TITLE
Replace astropy coordinate transform

### ISSUE THREAD

**Issue by gusbeane** [joshspeagle/brutus#39]
Currently takes up ~3.5% of the runtime, possibly can be shaved with a homemade solution

**Comment by joshspeagle** [comment]
This turns out to be a negligible portion of the runtime per object using `BruteForce`, but would probably have a non-negligible amount of overhead if we ever wanted to use brutus in "sampling" mode (since I do actually have model generation utilities using `isochrone` and `SEDmaker`). I think we can consider this lower priority for now but should still plan to implement it just to prepare for this.

**Comment by gusbeane** [comment]
With preliminary performance tests of 578b241 I was finding it still takes ~0.1s/obj, so I think it should still be targeted before the next flagship run
